# Generated by Django 4.0.4 on 2022-04-25 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCommunityMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.community')),
            ],
        ),
    ]
