# Generated by Django 4.0.4 on 2022-04-27 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnpassPopularEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
                ('attendee', models.IntegerField(default=0)),
                ('series_title', models.CharField(max_length=200)),
                ('series_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyYoutubeSubscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QiitaDailyPV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QiitaMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QiitaTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TotalMemberKPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterDailyPV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePopularVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=200)),
                ('view_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ZennDailyPV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZennTopics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QiitaOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('username', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyFacebookMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.community')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
                ('event_id', models.CharField(max_length=50)),
                ('view', models.IntegerField(default=0)),
                ('unique', models.IntegerField(default=0)),
                ('attendee', models.IntegerField(default=0)),
                ('sessiontime', models.IntegerField(default=0)),
                ('first_visitor', models.IntegerField(default=-1)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.community')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEventRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.IntegerField(default=0)),
                ('unique', models.IntegerField(default=0)),
                ('attendee', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
        migrations.CreateModel(
            name='ZennPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
                ('liked', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField(default=0)),
                ('twitter_screen_name', models.CharField(default='undefined', max_length=100)),
                ('last_tweeted_lgtm_count', models.IntegerField(default=0)),
                ('topics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zenntopics')),
            ],
            options={
                'unique_together': {('url', 'topics_id')},
            },
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('follower_count', models.IntegerField(default=0)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.twittertag')),
            ],
            options={
                'unique_together': {('url', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='QiitaPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=200)),
                ('lgtm', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField(default=0)),
                ('first_post_date', models.DateField(default=django.utils.timezone.now)),
                ('twitter_screen_name', models.CharField(default='undefined', max_length=100)),
                ('last_tweeted_lgtm_count', models.IntegerField(default=0)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qiitatag')),
            ],
            options={
                'unique_together': {('url', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='ConnpassMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_url', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.community')),
            ],
            options={
                'unique_together': {('profile_url', 'community_id')},
            },
        ),
    ]
