# Generated by Django 4.0.4 on 2022-05-09 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('livestreaming', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
