# Generated by Django 4.0.4 on 2022-05-11 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id_qiita', models.CharField(max_length=50, unique=True)),
                ('id_zenn', models.CharField(max_length=50, unique=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAtSeminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAtEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leader')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roleatseminar')),
            ],
        ),
    ]
