# Generated by Django 4.0.4 on 2022-05-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_leader_roleatseminar_attendanceatevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleAtSeminar',
            new_name='RoleAtEvent',
        ),
    ]
