# Generated by Django 4.0.4 on 2022-05-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_roleatevent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuterCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityCollaboration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('outercommunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outercommunity')),
            ],
        ),
    ]
