# Generated by Django 4.0.4 on 2022-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_outercommunity_communitycollaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outercommunity',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='communitycollaboration',
            unique_together={('event_id', 'outercommunity_id')},
        ),
    ]
