# Generated by Django 4.0.4 on 2022-05-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_outercommunity_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
