# Generated by Django 4.0.4 on 2022-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outercommunity',
            options={'ordering': ['name']},
        ),
    ]
