# Generated by Django 4.0.4 on 2022-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_outercommunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='lae',
            field=models.BooleanField(default=False),
        ),
    ]
