# Generated by Django 4.0.4 on 2022-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_leader_lae'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='id_connpass',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id_qiita',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id_zenn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
