# Generated by Django 4.0.4 on 2022-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_leader_id_connpass_alter_leader_id_qiita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='id_connpass',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id_qiita',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id_zenn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
