# Generated by Django 4.0.4 on 2022-05-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_leader_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['-lae', 'name']},
        ),
    ]
